function [constraining_curve_x, constraining_curve_y, x_LT, x_RT] = ...
    get_allocation_polygon( ...
    i, years, total_rate, ...
    storage_resource_total, ...
    step_curve_start, step_curve_end, ...
    allocation_duration)

% Helper: function to get interpolated growth value at arbitrary time
growth_at = @(t) interp1(years, total_rate, t, 'linear', 'extrap');

x_LT = NaN;
x_RT = NaN;

%% Define x-boundaries

% define x boundaries for region i
% LB: left bottom
% LT: left top
% RT: right top
% RB: right bottom
if i == 1
    x_LB = 2030;
    x_RB = 2030 + allocation_duration - 1;
else
    x_LB = step_curve_start(i-1);
    x_RB = step_curve_end(i-1);
end

idx1 = find(years >= x_LB, 1, 'first');
idx4 = find(years >= x_RB, 1, 'first');

%% Define top boundaries if current resource level intersects growth curve
% if i < allocation_step
if storage_resource_total(i) < max(total_rate)

    x_LT = step_curve_start(i);
    x_RT = step_curve_end(i);

    idx2 = find(years >= x_LT, 1, 'first');
    idx3 = find(years >= x_RT, 1, 'first');
end

%% Build polygon

% Build constraining curves for each region
if i == 1

    lower_rate = 0;

    if storage_resource_total(i) < total_rate(1) && ...
       storage_resource_total(i) < total_rate(end)

        constraining_curve_x = [x_LB; x_LB; x_RB; x_RB];

        constraining_curve_y = [lower_rate; ...
                                storage_resource_total(i); ...
                                storage_resource_total(i); ...
                                lower_rate];

    elseif storage_resource_total(i) < total_rate(1) && ...
           storage_resource_total(i) >= total_rate(end)

        base_x = transpose(floor(x_RB):-1:ceil(x_LB));

        constraining_curve_x = [x_LB; ...
                                x_LB; ...
                                x_RT; ...
                                years(idx3:(idx4-1)); ...
                                x_RB; ...
                                x_RB; ...
                                base_x];

        constraining_curve_y = [lower_rate; ...
                                storage_resource_total(i); ...
                                storage_resource_total(i); ...
                                total_rate(idx3:(idx4-1)); ...
                                min(growth_at(x_RB),storage_resource_total(i)); ...
                                lower_rate; ...
                                zeros(size(base_x))];

    else

        plateau_x = transpose(ceil(x_LT):floor(x_RT));
        base_x    = transpose(floor(x_RB):-1:ceil(x_LB));

        constraining_curve_x = [x_LB; ...
                                x_LB; ...
                                years(idx1:(idx2-1)); ...
                                x_LT; ...
                                plateau_x; ...
                                x_RT; ...
                                years(idx3:(idx4-1)); ...
                                x_RB; ...
                                x_RB; ...
                                base_x];

        constraining_curve_y = [lower_rate; ...
                                growth_at(x_LB); ...
                                total_rate(idx1:(idx2-1)); ...
                                growth_at(x_LT); ...
                                growth_at(x_LT)*ones(size(plateau_x)); ...
                                storage_resource_total(i); ...
                                total_rate(idx3:(idx4-1)); ...
                                min(growth_at(x_RB),storage_resource_total(i)); ...
                                lower_rate; ...
                                zeros(size(base_x))];
    end

else

    lower_rate = storage_resource_total(i-1);

    if storage_resource_total(i) < max(total_rate)

        if storage_resource_total(i) < total_rate(1) && ...
           storage_resource_total(i) < total_rate(end)

            constraining_curve_x = [x_LB; x_LB; x_RB; x_RB];

            constraining_curve_y = [lower_rate; ...
                                    storage_resource_total(i); ...
                                    storage_resource_total(i); ...
                                    lower_rate];

        elseif storage_resource_total(i) < total_rate(1) && ...
               storage_resource_total(i) >= total_rate(end)

            base_x = transpose(floor(x_RB):-1:ceil(x_LB));

            constraining_curve_x = [x_LB; ...
                                    x_LB; ...
                                    x_RT; ...
                                    years(idx3:(idx4-1)); ...
                                    x_RB; ...
                                    x_RB; ...
                                    base_x];

            constraining_curve_y = [lower_rate; ...
                                    storage_resource_total(i); ...
                                    storage_resource_total(i); ...
                                    total_rate(idx3:(idx4-1)); ...
                                    min(growth_at(x_RB),storage_resource_total(i)); ...
                                    lower_rate; ...
                                    lower_rate*ones(size(base_x))];

        else

            plateau_x = transpose(ceil(x_LT):floor(x_RT));
            base_x    = transpose(floor(x_RB):-1:ceil(x_LB));

            constraining_curve_x = [x_LB; ...
                                    x_LB; ...
                                    years(idx1:(idx2-1)); ...
                                    x_LT; ...
                                    plateau_x; ...
                                    x_RT; ...
                                    years(idx3:(idx4-1)); ...
                                    x_RB; ...
                                    x_RB; ...
                                    base_x];

            constraining_curve_y = [lower_rate; ...
                                    growth_at(x_LB); ...
                                    total_rate(idx1:(idx2-1)); ...
                                    growth_at(x_LT); ...
                                    growth_at(x_LT)*ones(size(plateau_x)); ...
                                    storage_resource_total(i); ...
                                    total_rate(idx3:(idx4-1)); ...
                                    min(growth_at(x_RB),storage_resource_total(i)); ...
                                    lower_rate; ...
                                    lower_rate*ones(size(base_x))];
        end

    else

        base_x = transpose(floor(x_RB):-1:ceil(x_LB));

        constraining_curve_x = [x_LB; ...
                                x_LB; ...
                                years(idx1:(idx4-1)); ...
                                x_RB; ...
                                base_x];

        constraining_curve_y = [lower_rate; ...
                                growth_at(x_LB); ...
                                total_rate(idx1:(idx4-1)); ...
                                lower_rate; ...
                                lower_rate*ones(size(base_x))];
    end
end

end